### ISSUE TITLE
uav_mass parameter is missed in robot configure files

### ISSUE THREAD

**Issue by MJavadZallaghi** [ctu-mrs/mrs_uav_deployment#7]
I'm working on using mrs_uav_system on my X650 robot (similar to T650). While using mrs_uav_deployment based on your wiki for real world tests, noticed in [just_flying](https://github.com/ctu-mrs/mrs_uav_deployment/tree/master/tmux/just_flying) example, the `uav_mass` parameter in the [platform configure file for t650](https://github.com/ctu-mrs/mrs_uav_deployment/blob/master/config/mrs_uav_system/t650.yaml) is missed.

So at the moment it's like this:
```yaml
motor_params:
  n_motors: 4
  a: 0.32
  b: -0.437
```
that causes this error:
```bash
[UavManager]: initializing
...
[ERROR]: Could not load non-optional parameter /uav1/uav_manager/uav_mass
```
![Image](https://github.com/user-attachments/assets/7e858113-818a-46fa-b55d-4ce592f8db1b)

and with this correction the error would be solved:
```yaml
uav_mass: 3.5 # Missed Parameter
motor_params:
  n_motors: 4
  a: 0.32
  b: -0.437
````

I suggest you correct this issue with adding `uav_mass` to platform yaml files in the folder [mrs_uav_deployment/config/mrs_uav_system](https://github.com/ctu-mrs/mrs_uav_deployment/tree/master/config/mrs_uav_system).
